o101 ;Argument List
(print,Argument list:)
(print,  1 = #<1>; A = #<avalue>)
(print,  2 = #<2>; B = #<bvalue>)
(print,  3 = #<3>; C = #<cvalue>)
(print,  4 = #<4>; I = #<ivalue>)
(print,  5 = #<5>; J = #<jvalue>)
(print,  6 = #<6>; K = #<kvalue>)
(print,  7 = #<7>; D = #<dvalue>)
(print,  8 = #<8>; E = #<evalue>)
(print,  9 = #<9>; F = #<fvalue>)
(print,  10 = #<10>; G = #<gvalue>)
(print,  11 = #<11>; H = #<hvalue>)
(print,  12 = #<12>; L = #<lvalue>)
(print,  13 = #<13>; M = #<mvalue>)
(print,  14 = #<14>; N = #<nvalue>)
(print,  15 = #<15>; O = #<ovalue>)
(print,  16 = #<16>; P = #<pvalue>)
(print,  17 = #<17>; Q = #<qvalue>)
(print,  18 = #<18>; R = #<rvalue>)
(print,  19 = #<19>; S = #<svalue>)
(print,  20 = #<20>; T = #<tvalue>)
(print,  21 = #<21>; U = #<uvalue>)
(print,  22 = #<22>; V = #<vvalue>)
(print,  23 = #<23>; W = #<wvalue>)
(print,  24 = #<24>; X = #<xvalue>)
(print,  25 = #<25>; Y = #<yvalue>)
(print,  26 = #<26>; Z = #<zvalue>)

(print,---------------------------------------------)
(print,val #<val>)
(print,_val #<_val>)
(print,_expr #<_expr>)


(print,---------------------------------------------)
(print,_hw_mpg_mode #<_hw_mpg_mode>)
(print,_hw_mpg_axis #<_hw_mpg_axis>)
(print,_hw_mpg_key #<_hw_mpg_key>)
(print,_hw_mpg_delta #<_hw_mpg_delta>)
(print,_hw_mpg_value #<_hw_mpg_value>)
(print,_hw_mpg_axisnum #<_hw_mpg_axisnum>)
(print,_hw_mpg_velocity #<_hw_mpg_velocity>)
(print,_hw_returnparam #<_hw_returnparam>)
(print,_hw_mpg_custom #<_hw_mpg_custom>)
(print,---------------------------------------------)
M99
